var res = {
  HealTexture_png: "res/Heal_texture.png",
  DotTexture_png: "res/Dot_texture.png",
  particle_texture: "res/Dot_texture.png",
  chara_princessselect_10: "res/char/chara_princessselect_10.png",
  chara_princessselect_11: "res/char/chara_princessselect_11.png",
  chara_princessselect_12: "res/char/chara_princessselect_12.png",
  ss_BattleScene_bg1: "res/field/ss_BattleScene_bg1.jpg",
  ss_BattleScene_bg2: "res/field/ss_BattleScene_bg2.jpg",
  ss_BattleScene_bg3: "res/field/ss_BattleScene_bg3.jpg",
  chara_enemy_1: "res/char/chara_enemy_1.png",
  chara_enemy_2: "res/char/chara_enemy_2.png",
  chara_enemy_3: "res/char/chara_enemy_3.png",
  chara_enemy_4: "res/char/chara_enemy_4.png",
  chara_enemy_5: "res/char/chara_enemy_5.png",
  chara_enemy_6: "res/char/chara_enemy_6.png",
  FireTexture0_plist: "res/effect/Fire_texture0.plist",
  FireTexture1_plist: "res/effect/Fire_texture1.plist",
  FireTexture2_plist: "res/effect/Fire_texture2.plist",
  FireTexture3_plist: "res/effect/Fire_texture3.plist",
  FireTexture4_plist: "res/effect/Fire_texture4.plist",
  WaterTexture1_plist: "res/effect/Water_texture1.plist",
  WaterTexture2_plist: "res/effect/Water_texture2.plist",
  WaterTexture3_plist: "res/effect/Water_texture3.plist",
  WaterTexture4_plist: "res/effect/Water_texture4.plist",
  WoodTexture1_plist: "res/effect/Wood_texture1.plist",
  WoodTexture2_plist: "res/effect/Wood_texture2.plist",
  WoodTexture3_plist: "res/effect/Wood_texture3.plist",
  WoodTexture4_plist: "res/effect/Wood_texture4.plist",
  HealTexture1_plist: "res/effect/Heal_texture1.plist",
  SlipTexture1_plist: "res/effect/Slip_texture1.plist",
  hibasiraTexture1_plist: "res/effect/hibasira1_texture.plist",
  hibasiraTexture21_plist: "res/effect/hibasira3_texture.plist",
  waterTexture1_plist: "res/effect/water1_texture.plist",
  waterTexture21_plist: "res/effect/water2_texture.plist",
  wordTexture1_plist: "res/effect/word1_texture.plist",
  wordTexture21_plist: "res/effect/word2_texture.plist",
  yamiTexture1_plist: "res/effect/yami1_texture.plist",
  yamiTexture21_plist: "res/effect/yami3_texture.plist",
  yamiTexture31_plist: "res/effect/yami4_texture.plist",

};

var g_resources = [];
for (var i in res) {
  g_resources.push(res[i]);
}
